### ISSUE TITLE
Specify db in redis configuration?

### ISSUE THREAD

**Issue by pjb3** [jxa/resque-clojure#8]
Is it possible to specify a db to use in addition to a host and port, like redis-clojure does?  Also, is there any reason not to have resque-clojure use redis-clojure instead of it's own internal redis client?

**Comment by jxa** [comment]
I see that there is an active fork of redis-clojure. At the time I started working on resque-clojure it didn't seem quite so well maintained, so I rolled my own. Do you have experience with the redis-clojure lib and if so, would you prefer it over jedis?

As for selecting the database, I will add the feature soon.

**Comment by mrgordon** [comment]
Obviously it would be convenient for legacy purposes if a db could be specified, but I wanted to point out that the db feature is on its way to deprecation and separate redis-server instances on different ports is now "best practice". We've been working on migrating away from dbs for this reason.
